name: Reuseble Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the deployment Operation
        value: ${{ jobs.deploy.outcome }}
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  deploy:
    outputs: 
      outcome: ${{ steps.result.outputs.exit }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls -la
      - name: Output Information
        run: echo "Deploy...."
      - name: Set result Output
        id: result
        run: echo "exit=Sucesss" >> $GITHUB_OUTPUT